# Site settings
title:          pinkys canon
description:    "how to take over the world"
url:            "https://pinkyscanon.net"

# Author
author:
  name:         l33tus
  url:          https://l33tus.net
  email:        l33tus@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
